DATABASE    human                       /tzu-share/resources/bowtie2/human_hg38
DATABASE    ecoli                       /tzu-share/resources/bowtie2/ecoli
DATABASE    mesomycoplasma_hyorhinis    /tzu-share/resources/bowtie2/mesomycoplasma_hyorhinis
DATABASE    mycoplasma_fermentans       /tzu-share/resources/bowtie2/mycoplasma_fermentans
DATABASE    saccharomyces_cerevisiae    /tzu-share/resources/bowtie2/saccharomyces_cerevisiae
DATABASE    mesomycoplasma_hyorhinis_B  /tzu-share/resources/bowtie2/gcf_900476065
ALIGNER     bowtie2